export const EXTENSION_NAME = "ComfyPencil.Studio";
export const STUDIO_NODE_ID = "ComfyPencilStudio";
export const API_PREFIX = "/comfypencil";
export const SIDEBAR_TAB_ID = "comfypencilSidebar";
export const DEFAULT_PRIMARY_COLOR = "#111111";
export const DEFAULT_SECONDARY_COLOR = "#ffffff";

export const COMMANDS = {
  OPEN_SELECTED: "ComfyPencil.OpenSelectedStudio",
  SAVE_ACTIVE: "ComfyPencil.SaveActiveStudio",
  OPEN_HELP: "ComfyPencil.OpenStudioHelp",
};

export const TOOLS = [
  { id: "brush", label: "Brush", icon: "B" },
  { id: "eraser", label: "Erase", icon: "E" },
  { id: "blend", label: "Blend", icon: "M" },
  { id: "fill", label: "Fill", icon: "G" },
  { id: "eyedropper", label: "Pick", icon: "I" },
  { id: "pan", label: "Pan", icon: "H" },
];

export const TOOL_DESCRIPTIONS = {
  brush: "Build color with directional tips, pressure response, scatter, and wet mix.",
  eraser: "Erase with the same shape and pressure controls as the brush.",
  blend: "Smudge nearby color with pickup, drag strength, and softer edge shape.",
  fill: "Flood fill using threshold and layer sampling rules.",
  eyedropper: "Sample visible color from the canvas composite.",
  pan: "Move around the canvas without affecting paint.",
};

const BRUSH_ENGINE_DEFAULTS = {
  roundness: 1,
  scatter: 0,
  density: 0.55,
  pressureSize: 0.6,
  pressureOpacity: 0.3,
  wetMix: 0,
  speedThin: 0.12,
  speedOpacity: 0.08,
  rotationJitter: 0.05,
  strokeJitter: 0,
  strokeFalloff: 0,
  stampRotation: 0,
  stabilization: 0,
  motionFilter: 0,
  motionFilterExpression: 0.5,
  startTaper: null,
  endTaper: null,
  taperOpacity: 0.22,
  tipSharpness: 0.5,
  shapeTextureId: "",
  shapeTextureData: "",
  shapeTextureScale: 1,
  shapeCount: 0,
  shapeCountJitter: 0,
  shapeAzimuth: 1,
  grainTextureId: "",
  grainTextureData: "",
  grainScale: 0.45,
  grainDepth: 0.35,
  grainContrast: 0.5,
  grainMovement: "rolling",
  renderMode: "build",
  renderIntensity: 0.5,
  wetEdges: 0,
  burntEdges: 0,
  luminanceBlend: 0,
  wetDilution: 0.35,
  wetCharge: 0.5,
  wetAttack: 0.4,
  wetPull: 0.35,
  wetGrade: 0.4,
  wetBlur: 0.14,
  hueStampJitter: 0,
  saturationStampJitter: 0,
  brightnessStampJitter: 0,
  hueStrokeJitter: 0,
  saturationStrokeJitter: 0,
  brightnessStrokeJitter: 0,
  sizeJitter: 0,
  opacityJitter: 0,
  flowJitter: 0,
  speedScatter: 0,
  tiltSize: 0,
  tiltOpacity: 0,
  tiltScatter: 0,
  tiltRotation: 0,
  previewScale: 1,
  previewTilt: 0,
  minimumSize: 0,
  maximumOpacity: 1,
  materialDepth: 0,
  materialShine: 0,
  materialRoughness: 0.5,
  aboutAuthor: "",
  aboutVersion: "",
  aboutNotes: "",
};

export const BLEND_MODES = [
  { value: "normal", label: "Normal", canvas: "source-over" },
  { value: "multiply", label: "Multiply", canvas: "multiply" },
  { value: "screen", label: "Screen", canvas: "screen" },
  { value: "overlay", label: "Overlay", canvas: "overlay" },
  { value: "soft-light", label: "Soft Light", canvas: "soft-light" },
  { value: "add", label: "Add", canvas: "lighter" },
];

export const CANVAS_SYMMETRY_OPTIONS = [
  { value: "off", label: "Off" },
  { value: "vertical", label: "Vertical" },
  { value: "horizontal", label: "Horizontal" },
  { value: "quadrant", label: "Quadrant" },
];

export const STROKE_CONSTRAINT_OPTIONS = [
  { value: 0, label: "Off" },
  { value: 45, label: "45 deg Snap" },
  { value: 30, label: "30 deg Snap" },
  { value: 15, label: "15 deg Snap" },
];

export const BRUSH_PRESETS = [
  {
    id: "pencil",
    label: "Pencil",
    libraryGroup: "sketching",
    tool: "brush",
    size: 12,
    opacity: 0.95,
    flow: 0.28,
    hardness: 0.92,
    spacing: 0.08,
    smoothing: 0.35,
    grain: 0.26,
    taper: 0.42,
    smudgeStrength: 0.4,
    fillTolerance: 18,
    sampleAllLayers: true,
    roundness: 0.72,
    scatter: 0.1,
    density: 0.56,
    pressureSize: 0.84,
    pressureOpacity: 0.42,
    wetMix: 0.06,
    speedThin: 0.22,
    speedOpacity: 0.12,
    rotationJitter: 0.08,
  },
  {
    id: "ink",
    label: "Ink",
    libraryGroup: "inking",
    tool: "brush",
    size: 8,
    opacity: 1,
    flow: 0.85,
    hardness: 1,
    spacing: 0.06,
    smoothing: 0.55,
    grain: 0.05,
    taper: 0.22,
    smudgeStrength: 0.25,
    fillTolerance: 12,
    sampleAllLayers: true,
    roundness: 0.54,
    scatter: 0.02,
    density: 0.26,
    pressureSize: 0.52,
    pressureOpacity: 0.24,
    wetMix: 0.02,
    speedThin: 0.34,
    speedOpacity: 0.2,
    rotationJitter: 0.03,
  },
  {
    id: "marker",
    label: "Marker",
    libraryGroup: "painting",
    tool: "brush",
    size: 24,
    opacity: 0.75,
    flow: 0.22,
    hardness: 0.65,
    spacing: 0.16,
    smoothing: 0.42,
    grain: 0.08,
    taper: 0.18,
    smudgeStrength: 0.2,
    fillTolerance: 24,
    sampleAllLayers: true,
    roundness: 0.42,
    scatter: 0.04,
    density: 0.42,
    pressureSize: 0.18,
    pressureOpacity: 0.08,
    wetMix: 0.16,
    speedThin: 0.06,
    speedOpacity: 0.04,
    rotationJitter: 0.04,
  },
  {
    id: "airbrush",
    label: "Airbrush",
    libraryGroup: "airbrush",
    tool: "brush",
    size: 42,
    opacity: 0.6,
    flow: 0.08,
    hardness: 0.18,
    spacing: 0.14,
    smoothing: 0.65,
    grain: 0.04,
    taper: 0.08,
    smudgeStrength: 0.18,
    fillTolerance: 22,
    sampleAllLayers: true,
    roundness: 1,
    scatter: 0.46,
    density: 0.78,
    pressureSize: 0.18,
    pressureOpacity: 0.72,
    wetMix: 0.34,
    speedThin: 0.04,
    speedOpacity: 0.14,
    rotationJitter: 0.02,
  },
  {
    id: "paint-round",
    label: "Paint",
    libraryGroup: "painting",
    tool: "brush",
    size: 26,
    opacity: 0.84,
    flow: 0.42,
    hardness: 0.58,
    spacing: 0.11,
    smoothing: 0.52,
    grain: 0.12,
    taper: 0.28,
    smudgeStrength: 0.28,
    fillTolerance: 20,
    sampleAllLayers: true,
    roundness: 0.82,
    scatter: 0.12,
    density: 0.62,
    pressureSize: 0.54,
    pressureOpacity: 0.34,
    wetMix: 0.52,
    speedThin: 0.14,
    speedOpacity: 0.08,
    rotationJitter: 0.06,
  },
  {
    id: "charcoal",
    label: "Charcoal",
    libraryGroup: "textures",
    tool: "brush",
    size: 28,
    opacity: 0.78,
    flow: 0.24,
    hardness: 0.48,
    spacing: 0.22,
    smoothing: 0.32,
    grain: 0.44,
    taper: 0.36,
    smudgeStrength: 0.36,
    fillTolerance: 28,
    sampleAllLayers: true,
    roundness: 0.56,
    scatter: 0.32,
    density: 0.88,
    pressureSize: 0.74,
    pressureOpacity: 0.48,
    wetMix: 0.12,
    speedThin: 0.18,
    speedOpacity: 0.12,
    rotationJitter: 0.1,
  },
  {
    id: "soft-blend",
    label: "Soften",
    libraryGroup: "blend",
    tool: "blend",
    size: 34,
    opacity: 0.28,
    flow: 0.16,
    hardness: 0.18,
    spacing: 0.1,
    smoothing: 0.5,
    grain: 0,
    taper: 0.06,
    smudgeStrength: 0.72,
    fillTolerance: 18,
    sampleAllLayers: true,
    roundness: 0.88,
    scatter: 0.08,
    density: 0.52,
    pressureSize: 0.28,
    pressureOpacity: 0.22,
    wetMix: 0.24,
    speedThin: 0.04,
    speedOpacity: 0.06,
    rotationJitter: 0.02,
  },
].map((preset) => ({ ...BRUSH_ENGINE_DEFAULTS, ...preset }));

export const DEFAULT_SWATCHES = [
  "#111111",
  "#f8f6ef",
  "#c74b40",
  "#dd8b37",
  "#e9cf63",
  "#5b8f51",
  "#2f7498",
  "#4658b0",
  "#7b4bb3",
  "#f07a97",
];

export const KEY_HINTS = {
  brush: "B",
  eraser: "E",
  blend: "M",
  fill: "G",
  eyedropper: "I",
  pan: "H or Space",
};
